# Generated by Django 4.2.7 on 2025-09-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_chatmessage_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session this message belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="analytics.analysissession",
            ),
        ),
    ]