# Generated by Django 4.2.7 on 2025-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_alter_chatmessage_session_notnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="max_tokens_per_month",
            field=models.PositiveIntegerField(
                default=10000000,
                help_text="Maximum tokens allowed per month",
            ),
        ),
    ]