# Generated by Django 4.2.7 on 2025-09-28 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_alter_user_max_tokens_per_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Interpretation title", max_length=255),
                ),
                (
                    "content",
                    models.TextField(help_text="AI-generated interpretation content"),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Analysis"),
                            ("table", "Table Analysis"),
                            ("chart", "Chart Analysis"),
                            ("mixed", "Mixed Analysis"),
                        ],
                        help_text="Type of analysis being interpreted",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        help_text="LLM model used for interpretation", max_length=100
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score for the interpretation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tokens used for interpretation"
                    ),
                ),
                (
                    "interpretation_data",
                    models.JSONField(
                        default=dict,
                        help_text="Original analysis data that was interpreted",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context used for interpretation",
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Quality score for the interpretation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="User feedback on interpretation helpfulness",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        help_text="Analysis result this interpretation relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interpretations",
                        to="analytics.analysisresult",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this interpretation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interpretations",
                        to="analytics.analysissession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requested this interpretation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interpretations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Interpretation",
                "verbose_name_plural": "AI Interpretations",
                "db_table": "analytics_ai_interpretation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_a_user_id_9a292f_idx",
                    ),
                    models.Index(
                        fields=["analysis_result"],
                        name="analytics_a_analysi_56639a_idx",
                    ),
                    models.Index(
                        fields=["session"], name="analytics_a_session_e52921_idx"
                    ),
                    models.Index(
                        fields=["analysis_type"], name="analytics_a_analysi_0d807f_idx"
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="analytics_a_confide_a1f162_idx",
                    ),
                ],
            },
        ),
    ]
