# Generated by Django 4.2.7 on 2025-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_aiinterpretation"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinterpretation",
            name="is_fallback",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a fallback response due to AI service issues",
            ),
        ),
    ]
